/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

/**
 *
 * @author rafael
 */
public class MenuAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public MenuAdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClientes = new javax.swing.JButton();
        jButtonCajeros = new javax.swing.JButton();
        jButtonAdministradores = new javax.swing.JButton();
        jButtonCuentas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setTitle("Menu Administradores");

        jButtonClientes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonCajeros.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonCajeros.setText("Cajeros");
        jButtonCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCajerosActionPerformed(evt);
            }
        });

        jButtonAdministradores.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonAdministradores.setText("Administradores");
        jButtonAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministradoresActionPerformed(evt);
            }
        });

        jButtonCuentas.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonCuentas.setText("Cuentas ");
        jButtonCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuentasActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdministradores)
                    .addComponent(jButtonCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonClientes)
                .addGap(46, 46, 46)
                .addComponent(jButtonCajeros)
                .addGap(58, 58, 58)
                .addComponent(jButtonAdministradores)
                .addGap(54, 54, 54)
                .addComponent(jButtonCuentas)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejadorClientesGUI().setVisible(true);
            }
        }); 
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuentasActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejadorCuentasGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonCuentasActionPerformed

    private void jButtonAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministradoresActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejadorAdmins().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonAdministradoresActionPerformed

    private void jButtonCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCajerosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejadorCajeros().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonCajerosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministradores;
    private javax.swing.JButton jButtonCajeros;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonCuentas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
