/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorAdministradores;
import controlador.ControladorBD;
import controlador.ControladorCajeros;
import controlador.ControladorClientes;
import modelo.Usuario;
import modelo.Administrador;
import modelo.Cajero;
import modelo.Cliente;
/**
 *
 * @author rafael
 */
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
public class CambiarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form CambiarContrasena
     */
    ControladorClientes contrCli;
    ControladorCajeros contrCaj;
    ControladorAdministradores contrAdmin;
    Usuario usu;
    ControladorBD contrBD;
    public CambiarContrasena(Usuario usu) {
        initComponents();
        this.usu = usu;
        contrBD = new ControladorBD();
        contrCli = new ControladorClientes();
        contrCaj = new ControladorCajeros();
        contrAdmin = new ControladorAdministradores();
        
        jToggleButton1.addItemListener(new ItemListener(){
 
            @Override
            public void itemStateChanged(ItemEvent itemEvent) {
                int estado = itemEvent.getStateChange();
                if(estado == ItemEvent.SELECTED){
                    jPasswordFieldActual.setEchoChar((char)0);
                } else {
                    jPasswordFieldActual.setEchoChar('*');
                }
            }
        });
        
        jToggleButton2.addItemListener(new ItemListener(){
 
            @Override
            public void itemStateChanged(ItemEvent itemEvent) {
                int estado = itemEvent.getStateChange();
                if(estado == ItemEvent.SELECTED){
                    jPasswordFieldNueva.setEchoChar((char)0);
                } else {
                    jPasswordFieldNueva.setEchoChar('*');
                }
            }
        });
        
        jToggleButton3.addItemListener(new ItemListener(){
 
            @Override
            public void itemStateChanged(ItemEvent itemEvent) {
                int estado = itemEvent.getStateChange();
                if(estado == ItemEvent.SELECTED){
                    jPasswordFieldNueva2.setEchoChar((char)0);
                } else {
                    jPasswordFieldNueva2.setEchoChar('*');
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCambiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jPasswordFieldActual = new javax.swing.JPasswordField();
        jPasswordFieldNueva = new javax.swing.JPasswordField();
        jPasswordFieldNueva2 = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setTitle("Cambio de Contraseña");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Cedula:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña Actual:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Nueva Contraseña:");

        jButtonCambiar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonCambiar.setText("Cambiar");
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Confirmar Contraseña:");

        jTextFieldCedula.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jPasswordFieldActual.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jPasswordFieldNueva.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jPasswordFieldNueva2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jToggleButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jToggleButton1.setText("👁️");

        jToggleButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jToggleButton2.setText("👁️");

        jToggleButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jToggleButton3.setText("👁️");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordFieldNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldNueva2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldActual))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButtonCambiar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jToggleButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButton3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jPasswordFieldActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jPasswordFieldNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jPasswordFieldNueva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1)))
                .addGap(56, 56, 56)
                .addComponent(jButtonCambiar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed
        
        Cliente cli = new Cliente();
        Administrador admin = new Administrador();
        Cajero caj = new Cajero();
        
        
        int idUsu = Integer.parseInt(jTextFieldCedula.getText());
        String pass = new String(jPasswordFieldActual.getPassword());
        
        // Se verifica el tipo de usuario para autenticar en el controlador correspondiente
        
        boolean auth = true;
        
        if(usu.getClass() == cli.getClass()){
            auth = contrCli.autenticar(idUsu, pass);
        }
        if(usu.getClass() == admin.getClass()){
            auth = contrAdmin.autenticar(idUsu, pass);
        }
        if(usu.getClass() == caj.getClass()){
            auth = contrCaj.autenticar(idUsu, pass);
        }
        
        // Si no se autenticó bien, no se hace nada más
        if(!auth){
            JOptionPane.showMessageDialog(null, "Cedula o contraseña incorrectas");
            return;
        }
            
            
        // Ahora se valida que las dos contraseñas ingresadas si coincidan:
        
        String newPass1 = new String(jPasswordFieldNueva.getPassword());
        String newPass2 = new String(jPasswordFieldNueva2.getPassword());
        
        if(!newPass1.equals(newPass2)){
            JOptionPane.showMessageDialog(null, "La confirmación de la contraseña no coincide");
            return;
        }
        
        // Ahora cambia la contraseña en el controlador respectivo:
        
        
        if(usu.getClass() == cli.getClass()){
            cli = new Cliente((Cliente)usu);
            cli.setContrasena(newPass1);
            
            contrCli.modificar(usu, cli);
            contrBD.modificarCliente(cli);
        }
        if(usu.getClass() == admin.getClass()){
            admin = new Administrador((Administrador)usu);
            admin.setContrasena(newPass1);
            
            contrAdmin.modificar(usu, admin);
            contrBD.modificarAdministrador(admin);
        }
        if(usu.getClass() == caj.getClass()){
            
            caj = new Cajero((Cajero)usu);
            caj.setContrasena(newPass1);
            
            contrCaj.modificar(usu, caj);
            contrBD.modificarCajero(caj);
        }
        
        JOptionPane.showMessageDialog(null, "Contraseña actualizada exitosamente");
        
    }//GEN-LAST:event_jButtonCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CambiarContrasena().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordFieldActual;
    private javax.swing.JPasswordField jPasswordFieldNueva;
    private javax.swing.JPasswordField jPasswordFieldNueva2;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
