/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorBD;
import controlador.ControladorCuentasAhorros;
import controlador.ControladorCuentasCorriente;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Cajero;
import modelo.Cliente;
import modelo.CuentaAhorros;
import modelo.CuentaCorriente;

/**
 *
 * @author rafael
 */
public class Consignar extends javax.swing.JFrame {

    /**
     * Creates new form TransaccionesCli
     */
    Cajero caj;
    ControladorCuentasAhorros contrAho;
    ControladorCuentasCorriente contrCorr;
    ControladorBD contrBD;
    
    public Consignar(Cajero caj) {
        initComponents();
        
        this.caj = caj;
        contrAho = new ControladorCuentasAhorros();
        contrCorr = new ControladorCuentasCorriente();
        contrBD = new ControladorBD();
        
        
        
        
        
        jToggleButton1.addItemListener(new ItemListener(){
 
            @Override
            public void itemStateChanged(ItemEvent itemEvent) {
                int estado = itemEvent.getStateChange();
                if(estado == ItemEvent.SELECTED){
                    jPasswordField.setEchoChar((char)0);
                } else {
                    jPasswordField.setEchoChar('*');
                }
            }
        });
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdCuenta = new javax.swing.JTextField();
        jTextFieldCedulaTitular = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonConsignar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBoxTipoCuenta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMonto = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();

        setTitle("Consignar");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Número de Cuenta:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Cedula del Titular:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Clave Cajero:");

        jTextFieldIdCuenta.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jTextFieldCedulaTitular.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldCedulaTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaTitularActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jButtonConsignar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonConsignar.setText("Consignar");
        jButtonConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsignarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Datos Cuenta");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Tipo de Cuenta:");

        jToggleButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jToggleButton1.setText("👁️");

        jComboBoxTipoCuenta.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBoxTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros", "Corriente" }));
        jComboBoxTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoCuentaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Monto:");

        jTextFieldMonto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMontoFocusGained(evt);
            }
        });
        jTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton1))
                                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTotal)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldCedulaTitular)
                                        .addComponent(jTextFieldIdCuenta)
                                        .addComponent(jComboBoxTipoCuenta, 0, 215, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButtonConsignar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCedulaTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotal)))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonConsignar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsignarActionPerformed
        
        String pass = new String(jPasswordField.getPassword());
        
        if(jTextFieldIdCuenta.getText().equals("") || jTextFieldCedulaTitular.getText().equals("") || jTextFieldMonto.getText().equals("")){
                jLabelTotal.setText("Digite datos de cuenta");
                jLabelTotal.setForeground(Color.red);
                System.out.println(jTextFieldCedulaTitular.getText()+" , "+jTextFieldCedulaTitular.getText());
                JOptionPane.showMessageDialog(null, "Hay almenos un campo vacío");
        }
        else{
            String numeroCuenta = jTextFieldIdCuenta.getText();
            int idTitular = Integer.parseInt(jTextFieldCedulaTitular.getText());
            float monto = Float.parseFloat(jTextFieldMonto.getText());

            if (monto <= 0){
                JOptionPane.showMessageDialog(null, "Ingrese un monto valido (no puede ser negativo)");
            }
            else{
            if(!pass.equals(caj.getContrasena())){
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
            else{
            if(jComboBoxTipoCuenta.getSelectedItem().equals("Ahorros"))
            {
                // Buscar la cuenta ahorros seleccionada:

                CuentaAhorros cuenta = new CuentaAhorros();
                cuenta.setIdCuentaAhorros(numeroCuenta);

                cuenta = (CuentaAhorros)contrAho.consultarUno(cuenta);

                if(cuenta.getIdCliente() != idTitular || cuenta.getSaldoCuentaAhorros() == 0.0f){
                    jLabelTotal.setText("Cuenta no encontrada");
                    jLabelTotal.setForeground(Color.red);
                    JOptionPane.showMessageDialog(null, "La cuenta digitada no existe");
                }
                else{
                    // Si la cuenta existe realiza la transacción


                        // Si los fondos alcanzan realiza la transacción:
                        
                        CuentaAhorros cuentaAux = new CuentaAhorros(cuenta);
                        cuentaAux.setSaldoCuentaAhorros(cuenta.getSaldoCuentaAhorros()+monto);
                        
                        contrAho.modificar(cuenta, cuentaAux);
                        contrBD.modificarCuentaAho(cuentaAux);
                        JOptionPane.showMessageDialog(null, "Transacción exitosa\n El nuevo saldo es: "+cuentaAux.getSaldoCuentaAhorros());
                    
                }
            }
            if(jComboBoxTipoCuenta.getSelectedItem().equals("Corriente")){
                // Buscar la cuenta corriente seleccionada:

                CuentaCorriente cuenta = new CuentaCorriente();
                cuenta.setIdCuentaCorriente(numeroCuenta);

                cuenta = (CuentaCorriente)contrCorr.consultarUno(cuenta);

                if(cuenta.getIdCliente() != idTitular || cuenta.getSaldoCuentaCorriente() == 0.0f){
                    jLabelTotal.setText("Cuenta no encontrada");
                    jLabelTotal.setForeground(Color.red);
                    JOptionPane.showMessageDialog(null, "La cuenta digitada no existe");
                }
                else{
                    // Si la cuenta existe realiza la transacción

                        // Si los fondos alcanzan realiza la transacción:
                        
                        CuentaCorriente cuentaAux = new CuentaCorriente(cuenta);
                        cuentaAux.setSaldoCuentaCorriente(cuenta.getSaldoCuentaCorriente()+monto);
                        
                        contrCorr.modificar(cuenta, cuentaAux);
                        contrBD.modificarCuentaCorr(cuentaAux);
                        JOptionPane.showMessageDialog(null, "Transacción exitosa\n El nuevo saldo es: "+cuentaAux.getSaldoCuentaCorriente());
                        
                        
                    
                }
            }
        }
            }
        }
    }//GEN-LAST:event_jButtonConsignarActionPerformed

    private void jTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoActionPerformed

    private void jTextFieldCedulaTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaTitularActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextFieldMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMontoFocusGained
        // Actualizar el total disponible en la cuenta:
//        System.out.println("Focus gained");
        if(jTextFieldIdCuenta.getText().equals("") || jTextFieldCedulaTitular.getText().equals("")){
                jLabelTotal.setText("Digite datos de cuenta");
                jLabelTotal.setForeground(Color.red);
                System.out.println(jTextFieldCedulaTitular.getText()+" , "+jTextFieldCedulaTitular.getText());
        }
        else{
            String numeroCuenta = jTextFieldIdCuenta.getText();
            int idTitular = Integer.parseInt(jTextFieldCedulaTitular.getText());


            if(jComboBoxTipoCuenta.getSelectedItem().equals("Ahorros"))
            {
                // Buscar la cuenta ahorros seleccionada:

                CuentaAhorros cuenta = new CuentaAhorros();
                cuenta.setIdCuentaAhorros(numeroCuenta);

                cuenta = (CuentaAhorros)contrAho.consultarUno(cuenta);

                if(cuenta.getIdCliente() != idTitular || cuenta.getSaldoCuentaAhorros() == 0.0f){
                    jLabelTotal.setText("Cuenta no encontrada");
                    jLabelTotal.setForeground(Color.red);
                }
                else{
                    jLabelTotal.setText("Disponible: "+cuenta.getSaldoCuentaAhorros()+" $");
                    Color col = new Color(102,102,102);
                    jLabelTotal.setForeground(col);
                }
            }
            if(jComboBoxTipoCuenta.getSelectedItem().equals("Corriente")){
                // Buscar la cuenta corriente seleccionada:

                CuentaCorriente cuenta = new CuentaCorriente();
                cuenta.setIdCuentaCorriente(numeroCuenta);

                cuenta = (CuentaCorriente)contrCorr.consultarUno(cuenta);

                if(cuenta.getIdCliente() != idTitular || cuenta.getSaldoCuentaCorriente() == 0.0f){
                    jLabelTotal.setText("Cuenta no encontrada");
                    jLabelTotal.setForeground(Color.red);
                }
                else{
                    jLabelTotal.setText("Disponible: "+cuenta.getSaldoCuentaCorriente()+" $");
                    Color col = new Color(102,102,102);
                    jLabelTotal.setForeground(col);
                }
            }
        }
    }//GEN-LAST:event_jTextFieldMontoFocusGained

    private void jComboBoxTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Transferencias().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsignar;
    private javax.swing.JComboBox<String> jComboBoxTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldCedulaTitular;
    private javax.swing.JTextField jTextFieldIdCuenta;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
