/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorBD;
import controlador.ControladorClientes;
import excepciones.ValidarContrasena;
import excepciones.ValidarCorreo;
import excepciones.ValidarTelefono;
import excepciones.VerificarNombreUsuario;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author rafael
 */
public class InsertarCliente extends javax.swing.JFrame {

    /**
     * Creates new form InsertarCajero
     */
    ControladorClientes contrCli;
    ControladorBD contrBD;
    
    public InsertarCliente() {
        initComponents();
        contrCli = new ControladorClientes();
        contrBD = new ControladorBD();
        jLabelContFuerte.setText("");
        jLabelCorreoValido.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldContrasena = new javax.swing.JTextField();
        jLabelContFuerte = new javax.swing.JLabel();
        jLabelCorreoValido = new javax.swing.JLabel();
        jLabelValidacionNombre = new javax.swing.JLabel();
        jLabelValidacionApellidos = new javax.swing.JLabel();
        jLabelValidacionCedula = new javax.swing.JLabel();
        jLabelValidacionTelefono = new javax.swing.JLabel();
        jLabelValidacionDireccion = new javax.swing.JLabel();

        setTitle("Crear Cliente");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Cedula:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Telefono:");

        jTextFieldNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jTextFieldApellidos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyReleased(evt);
            }
        });

        jTextFieldCedula.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCedulaKeyReleased(evt);
            }
        });

        jTextFieldCorreo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoFocusGained(evt);
            }
        });
        jTextFieldCorreo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldCorreoInputMethodTextChanged(evt);
            }
        });
        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyTyped(evt);
            }
        });

        jTextFieldTelefono.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyReleased(evt);
            }
        });

        jButtonInsertar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonInsertar.setText("Crear");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Contraseña:");

        jTextFieldDireccion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jTextFieldContrasena.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContrasenaActionPerformed(evt);
            }
        });
        jTextFieldContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldContrasenaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelContFuerte)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorreo)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldDireccion)
                            .addComponent(jTextFieldContrasena)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidos)
                            .addComponent(jTextFieldCedula))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValidacionDireccion)
                            .addComponent(jLabelValidacionTelefono)
                            .addComponent(jLabelValidacionCedula)
                            .addComponent(jLabelValidacionApellidos)
                            .addComponent(jLabelValidacionNombre)
                            .addComponent(jLabelCorreoValido))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButtonInsertar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addComponent(jLabelCorreoValido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValidacionTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabelValidacionDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContFuerte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButtonInsertar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        
        Cliente cli= new Cliente();
        
        
        try{
            VerificarNombreUsuario.verificar(jTextFieldNombre.getText());
            ValidarCorreo.verificar(jTextFieldCorreo.getText());
            ValidarContrasena.verificar(jTextFieldContrasena.getText());
            VerificarNombreUsuario.verificar(jTextFieldApellidos.getText());
            ValidarTelefono.verificar(jTextFieldTelefono.getText());
            
            //Faltaría validar los datos ingresados
            cli.setCedula(Integer.parseInt(jTextFieldCedula.getText()));
            cli.setNombre(jTextFieldNombre.getText());
            cli.setApellido(jTextFieldApellidos.getText());
            cli.setCorreo(jTextFieldCorreo.getText());
            cli.setTelefono(Long.parseLong(jTextFieldTelefono.getText()));
            cli.setDireccion(jTextFieldDireccion.getText());
            cli.setContrasena(jTextFieldContrasena.getText());
            
            if(!contrCli.insertar(cli)){
            JOptionPane.showMessageDialog(null, "Error al insertar cliente (posible repetido)");
        }
        else{
            contrBD.insertarCliente(cli);
            JOptionPane.showMessageDialog(null, "Cliente insertado exitosamente");
            jTextFieldNombre.setText("");
            jTextFieldApellidos.setText("");
            jTextFieldCedula.setText("");
            jTextFieldCorreo.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldContrasena.setText("");
            jTextFieldDireccion.setText("");
            
            jLabelContFuerte.setText("");
            jLabelCorreoValido.setText("");
            jLabelValidacionApellidos.setText("");
            jLabelValidacionCedula.setText("");
            jLabelValidacionCedula.setText("");
            jLabelValidacionNombre.setText("");
            jLabelValidacionTelefono.setText("");
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
            
            
        }
       catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor verifique todos los campos marcados con (*) \n Los campos numericos no pueden tener letras");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Por favor verifique todos los campos marcados con (*) \n"+ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jTextFieldCorreoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldCorreoInputMethodTextChanged
        
    }//GEN-LAST:event_jTextFieldCorreoInputMethodTextChanged

    private void jTextFieldCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoFocusGained

    private void jTextFieldCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyTyped
        
    }//GEN-LAST:event_jTextFieldCorreoKeyTyped

    private void jTextFieldCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyReleased
        // TODO add your handling code here:
        try{
            ValidarCorreo.verificar(jTextFieldCorreo.getText());
            Color col =  new Color(0,102,0);
            jLabelCorreoValido.setForeground(col);
            jLabelCorreoValido.setText("Correo valido");
        }
        catch(ValidarCorreo e){
            jLabelCorreoValido.setForeground(Color.red);
            jLabelCorreoValido.setText("Correo no valido (*)");
        }  
    }//GEN-LAST:event_jTextFieldCorreoKeyReleased

    private void jTextFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContrasenaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldContrasenaActionPerformed

    private void jTextFieldContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContrasenaKeyReleased
        // TODO add your handling code here:
        
        try{
            ValidarContrasena.verificar(jTextFieldContrasena.getText());
            jLabelContFuerte.setText("La contraseña es fuerte");
            Color col =  new Color(0,102,0);
            jLabelContFuerte.setForeground(col);
        }
        catch(ValidarContrasena ex){
            jLabelContFuerte.setText("La contraseña es debil (*)");
            jLabelContFuerte.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jTextFieldContrasenaKeyReleased

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        // TODO add your handling code here:
        
        try{
            VerificarNombreUsuario.verificar(jTextFieldNombre.getText());
            jLabelValidacionNombre.setText("Nombre valido");
            Color col =  new Color(0,102,0);
            jLabelValidacionNombre.setForeground(col);
        }
        catch(VerificarNombreUsuario ex){
            jLabelValidacionNombre.setText(ex.getLittleMessage());
            jLabelValidacionNombre.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyReleased
        // TODO add your handling code here:
        
        try{
            VerificarNombreUsuario.verificar(jTextFieldApellidos.getText());
            jLabelValidacionApellidos.setText("Apellidos válidos");
            Color col =  new Color(0,102,0);
            jLabelValidacionApellidos.setForeground(col);
        }
        catch(VerificarNombreUsuario ex){
            jLabelValidacionApellidos.setText(ex.getLittleMessage());
            jLabelValidacionApellidos.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyReleased

    private void jTextFieldCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedulaKeyReleased
        // TODO add your handling code here:
        
        try{
            int cedula = Integer.parseInt(jTextFieldCedula.getText());
            jLabelValidacionCedula.setText("Cédula válida");
            Color col =  new Color(0,102,0);
            jLabelValidacionCedula.setForeground(col);
        }
        catch(NumberFormatException ex){
            jLabelValidacionCedula.setText("Debe ser numérica (*)");
            jLabelValidacionCedula.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldCedulaKeyReleased

    private void jTextFieldTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyReleased
        // TODO add your handling code here:
        
        try{
            ValidarTelefono.verificar(jTextFieldTelefono.getText());
            long telefono = Long.parseLong(jTextFieldTelefono.getText());
            jLabelValidacionTelefono.setText("Telefono valido");
            Color col =  new Color(0,102,0);
            jLabelValidacionTelefono.setForeground(col);
            
        }
        catch(ValidarTelefono ex){
            jLabelValidacionTelefono.setText("Debe tener almenos 10 digitos (*)");
            jLabelValidacionTelefono.setForeground(Color.red);
        }
        catch(NumberFormatException ex){
            jLabelValidacionTelefono.setText("Solo puede tener numeros (*)");
            jLabelValidacionTelefono.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jTextFieldTelefonoKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InsertarCajero().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelContFuerte;
    private javax.swing.JLabel jLabelCorreoValido;
    private javax.swing.JLabel jLabelValidacionApellidos;
    private javax.swing.JLabel jLabelValidacionCedula;
    private javax.swing.JLabel jLabelValidacionDireccion;
    private javax.swing.JLabel jLabelValidacionNombre;
    private javax.swing.JLabel jLabelValidacionTelefono;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
