/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorAdministradores;
import controlador.ControladorBD;
import excepciones.ValidarContrasena;
import excepciones.ValidarCorreo;
import excepciones.ValidarTelefono;
import excepciones.VerificarNombreUsuario;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.Administrador;

/**
 *
 * @author rafael
 */
public class InsertarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InsertarCajero
     */
    ControladorAdministradores contrAdmins;
    ControladorBD contrBD;
    
    public InsertarAdmin() {
        initComponents();
        contrAdmins = new ControladorAdministradores();
        contrBD = new ControladorBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldContrasena = new javax.swing.JTextField();
        jLabelCorreoValido = new javax.swing.JLabel();
        jLabelContFuerte = new javax.swing.JLabel();
        jLabelValidacionNombre = new javax.swing.JLabel();
        jLabelValidacionApellido = new javax.swing.JLabel();
        jLabelValidacionCedula = new javax.swing.JLabel();
        jLabelValidacionId = new javax.swing.JLabel();
        jLabelValidacionTelefono = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setTitle("Crear Administrador");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Identificador:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Telefono:");

        jTextFieldNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jTextFieldApellidos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyReleased(evt);
            }
        });

        jTextFieldCedula.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCedulaKeyReleased(evt);
            }
        });

        jTextFieldIdentificador.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIdentificadorKeyReleased(evt);
            }
        });

        jTextFieldCorreo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyReleased(evt);
            }
        });

        jTextFieldTelefono.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyReleased(evt);
            }
        });

        jButtonInsertar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonInsertar.setText("Crear");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Contraseña:");

        jTextFieldDireccion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jTextFieldContrasena.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextFieldContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldContrasenaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdentificador)
                            .addComponent(jTextFieldCorreo)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldApellidos)
                            .addComponent(jTextFieldCedula)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCorreoValido)
                                    .addComponent(jLabelValidacionNombre)
                                    .addComponent(jLabelValidacionApellido)
                                    .addComponent(jLabelValidacionCedula)
                                    .addComponent(jLabelValidacionId)
                                    .addComponent(jLabelValidacionTelefono)
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldDireccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInsertar)
                                .addGap(132, 132, 132))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelContFuerte)
                                    .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidacionId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCorreoValido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelValidacionTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelContFuerte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButtonInsertar)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        
        Administrador admin= new Administrador();
        
        //Faltaría validar los datos ingresados
        
        try{
            
         VerificarNombreUsuario.verificar(jTextFieldNombre.getText()); // Para el nombre del usuario
         ValidarCorreo.verificar(jTextFieldCorreo.getText()); // Para el correo
         VerificarNombreUsuario.verificar(jTextFieldApellidos.getText());   
         ValidarTelefono.verificar(jTextFieldTelefono.getText());
            
        admin.setCedula(Integer.parseInt(jTextFieldCedula.getText()));
        admin.setIdAdmin(Integer.parseInt(jTextFieldIdentificador.getText()));
        admin.setNombre(jTextFieldNombre.getText());
        admin.setApellido(jTextFieldApellidos.getText());
        admin.setCorreo(jTextFieldCorreo.getText());
        admin.setTelefono(Long.parseLong(jTextFieldTelefono.getText()));
        admin.setDireccion(jTextFieldDireccion.getText());
        admin.setContrasena(jTextFieldContrasena.getText());    
        
        // Agregar al controlador:
        
        if(!contrAdmins.insertar(admin)){
            JOptionPane.showMessageDialog(null, "Error al insertar administrador (posible repetido)");
        }
        else{
            contrBD.insertarAdmin(admin);
            JOptionPane.showMessageDialog(null, "Administrador insertado exitosamente");
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor verifique todos los campos marcados con (*) \n Los campos numericos no pueden tener letras");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Por favor verifique todos los campos marcados con (*) \n"+ex.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jTextFieldCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyReleased
        
        try{
            ValidarCorreo.verificar(jTextFieldCorreo.getText());
            Color col =  new Color(0,102,0);
            jLabelCorreoValido.setForeground(col);
            jLabelCorreoValido.setText("Correo valido");
        }
        catch(ValidarCorreo e){
            jLabelCorreoValido.setForeground(Color.red);
            jLabelCorreoValido.setText("Correo no valido (*)");
        }
        
        
    }//GEN-LAST:event_jTextFieldCorreoKeyReleased

    private void jTextFieldContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContrasenaKeyReleased
        // TODO add your handling code here:
        try{
            ValidarContrasena.verificar(jTextFieldContrasena.getText());
            jLabelContFuerte.setText("La contraseña es fuerte");
            Color col =  new Color(0,102,0);
            jLabelContFuerte.setForeground(col);
        }
        catch(ValidarContrasena ex){
            jLabelContFuerte.setText("La contraseña es debil");
            jLabelContFuerte.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldContrasenaKeyReleased

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        // TODO add your handling code here:
        try{
            VerificarNombreUsuario.verificar(jTextFieldNombre.getText());
            jLabelValidacionNombre.setText("Nombre valido");
            Color col =  new Color(0,102,0);
            jLabelValidacionNombre.setForeground(col);
        }
        catch(VerificarNombreUsuario ex){
            jLabelValidacionNombre.setText("Demasiado corto (*)");
            jLabelValidacionNombre.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyReleased
        // TODO add your handling code here:
        try{
            VerificarNombreUsuario.verificar(jTextFieldApellidos.getText());
            jLabelValidacionApellido.setText("Apellidos válidos");
            Color col =  new Color(0,102,0);
            jLabelValidacionApellido.setForeground(col);
        }
        catch(VerificarNombreUsuario ex){
            jLabelValidacionApellido.setText("Demasiado cortos (*)");
            jLabelValidacionApellido.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyReleased

    private void jTextFieldCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedulaKeyReleased
        // TODO add your handling code here:
        try{
            int cedula = Integer.parseInt(jTextFieldCedula.getText());
            jLabelValidacionCedula.setText("Cédula válida");
            Color col =  new Color(0,102,0);
            jLabelValidacionCedula.setForeground(col);
        }
        catch(NumberFormatException ex){
            jLabelValidacionCedula.setText("Debe ser numérica (*)");
            jLabelValidacionCedula.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldCedulaKeyReleased

    private void jTextFieldIdentificadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentificadorKeyReleased
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(jTextFieldIdentificador.getText());
            jLabelValidacionId.setText("Identificador valido");
            Color col =  new Color(0,102,0);
            jLabelValidacionId.setForeground(col);
        }
        catch(NumberFormatException ex){
            jLabelValidacionId.setText("Debe ser numerico (*)");
            jLabelValidacionId.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldIdentificadorKeyReleased

    private void jTextFieldTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyReleased
        // TODO add your handling code here:
        
        try{
            ValidarTelefono.verificar(jTextFieldTelefono.getText());
            long telefono = Long.parseLong(jTextFieldTelefono.getText());
            jLabelValidacionTelefono.setText("Telefono valido");
            Color col =  new Color(0,102,0);
            jLabelValidacionTelefono.setForeground(col);
            
        }
        catch(ValidarTelefono ex){
            jLabelValidacionTelefono.setText("Debe tener almenos 10 digitos (*)");
            jLabelValidacionTelefono.setForeground(Color.red);
        }
        catch(NumberFormatException ex){
            jLabelValidacionTelefono.setText("Solo puede tener numeros (*)");
            jLabelValidacionTelefono.setForeground(Color.red);
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyReleased

    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsertarCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InsertarCajero().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelContFuerte;
    private javax.swing.JLabel jLabelCorreoValido;
    private javax.swing.JLabel jLabelValidacionApellido;
    private javax.swing.JLabel jLabelValidacionCedula;
    private javax.swing.JLabel jLabelValidacionId;
    private javax.swing.JLabel jLabelValidacionNombre;
    private javax.swing.JLabel jLabelValidacionTelefono;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
