/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorBD;
import controlador.ControladorCajeros;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cajero;

/**
 *
 * @author rafael
 */
public class ManejadorCajeros extends javax.swing.JFrame {

    /**
     * Creates new form ManejadorCajeros
     */
    ControladorCajeros contrCaj;
    private DefaultTableModel model;
    Object rowData[];
    ControladorBD contrBD;
    
    public ManejadorCajeros() {
        initComponents();
        model = (DefaultTableModel)jTableCajeros.getModel();
        rowData = new Object [8];
        
        contrBD = new ControladorBD();
        contrCaj = new ControladorCajeros();
        // Llenar la tabla:
        actualizarTabla();
        
        jComboBoxSortBy.addActionListener(new ActionListener() {  
                                            public void actionPerformed(ActionEvent e) {
                                            
                                                if(jComboBoxSortBy.getSelectedItem().equals("Nombre")){
                                                    contrCaj.ordenarNombres();
                                                    actualizarTabla();
                                                }
                                                else{
                                                    contrCaj.ordenar();
                                                    actualizarTabla();
                                            }}
                                            });
        
    }

    
    private void llenarTabla(){
        for(Cajero caj:ControladorCajeros.arregloCajeros){
            rowData[0] = caj.getCedula();
            rowData[1] = caj.getIdCajero();
            rowData[2] = caj.getNombre();
            rowData[3] = caj.getApellido();
            rowData[4] = caj.getCorreo();
            rowData[5] = caj.getTelefono();
            rowData[6] = caj.getSueldo();
            rowData[7] = caj.getDireccion();
            
            model.addRow(rowData);
        }
    }
    
    
    private void vaciarTabla(){
        model.setRowCount(0);
    }
    
    private void actualizarTabla(){
        vaciarTabla();
        llenarTabla();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCajeros = new javax.swing.JTable();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSortBy = new javax.swing.JComboBox<>();

        setTitle("Manejador de Cajeros");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTableCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Identificador", "Nombre", "Apellidos", "Correo", "Telefono", "Sueldo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCajeros);

        jButtonNuevo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Ordenar Por:");

        jComboBoxSortBy.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBoxSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Cedula" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizar))
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarCajero().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        //tambien se debe consultar de la bd
        actualizarTabla();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int row = jTableCajeros.getSelectedRow();
        
        int cedula = (int)jTableCajeros.getModel().getValueAt(row, 0);
        
        
        Cajero caj = new Cajero();
        caj.setCedula(cedula);
        
        
        // También hay que eliminarlo de la bd
        
        if(!contrCaj.borrar(caj))
            JOptionPane.showMessageDialog(null, "Error al eliminar cajero");
        else{
            JOptionPane.showMessageDialog(null, "El cajero con cedula "+cedula+" ha sido eliminado exitosamente");
            contrBD.eliminarCajero(caj);
            model.removeRow(row);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int row = jTableCajeros.getSelectedRow();
        
        int cedula = (int)jTableCajeros.getModel().getValueAt(row, 0);
        
        
        Cajero caj = new Cajero();
        caj.setCedula(cedula);
        
        caj = (Cajero)contrCaj.consultarUno(caj);
        
        
        Cajero new_caj = new Cajero();
        
        // falta validar
        new_caj.setCedula(caj.getCedula());
        new_caj.setIdCajero(caj.getIdCajero());
        new_caj.setContrasena(caj.getContrasena());
        
        new_caj.setNombre(jTableCajeros.getModel().getValueAt(row, 2).toString());
        new_caj.setApellido(jTableCajeros.getModel().getValueAt(row, 3).toString());
        new_caj.setCorreo(jTableCajeros.getModel().getValueAt(row, 4).toString());
        new_caj.setTelefono(Long.parseLong(jTableCajeros.getModel().getValueAt(row, 5).toString()));
        new_caj.setSueldo(Double.parseDouble(jTableCajeros.getModel().getValueAt(row, 6).toString()));
        new_caj.setDireccion(jTableCajeros.getModel().getValueAt(row, 7).toString());
        
        
        if(!contrCaj.modificar(caj, new_caj))
            JOptionPane.showMessageDialog(null, "Error al modificar cajero");
        else
            contrBD.modificarCajero(new_caj);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManejadorCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManejadorCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManejadorCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManejadorCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManejadorCajeros().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox<String> jComboBoxSortBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCajeros;
    // End of variables declaration//GEN-END:variables
}
