/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGrafica;

import controlador.ControladorBD;
import controlador.ControladorCuentasAhorros;
import controlador.ControladorCuentasCorriente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.CuentaAhorros;
import modelo.CuentaCorriente;

/**
 *
 * @author rafael
 */
public class Retiros extends javax.swing.JFrame {

    /**
     * Creates new form Retiros
     */
    Cliente cli;
    ControladorCuentasAhorros contrCuentasAho;
    ControladorCuentasCorriente contrCuentasCorr;
    ControladorBD contrBD;
    public Retiros(Cliente cli) {
        initComponents();
        this.cli = cli;
        contrCuentasAho = new ControladorCuentasAhorros();
        contrCuentasCorr = new ControladorCuentasCorriente();
        contrBD = new ControladorBD();
        
        // Llenar combobox de cuentas:
        
        for(CuentaAhorros cuenta: contrCuentasAho.arregloCuentasAhorros){
            if (cuenta.getIdCliente() == cli.getCedula()){
                jComboCuenta.addItem("Ahorros - "+cuenta.getIdCuentaAhorros());
                jLabelTotal.setText("Disponible: " +cuenta.getSaldoCuentaAhorros()+" $");
                jComboCuenta.setSelectedItem("Ahorros - "+cuenta.getIdCuentaAhorros());
            }
        }
        
        for(CuentaCorriente cuenta: contrCuentasCorr.arregloCuentasCorriente){
            if (cuenta.getIdCliente() == cli.getCedula()){
                jComboCuenta.addItem("Corriente - "+cuenta.getIdCuentaCorriente());
                jLabelTotal.setText("Disponible: " +cuenta.getSaldoCuentaCorriente()+" $");
                jComboCuenta.setSelectedItem("Corriente - "+cuenta.getIdCuentaCorriente());
            }
        }
        
        
        
        jComboCuenta.addActionListener(new ActionListener() {  
                                            public void actionPerformed(ActionEvent e) {
                                                
                                                String cuenta = (String)jComboCuenta.getSelectedItem(); 
                                                String idCuenta = cuenta.replaceAll("[^0-9]", "");
                                                String tipo = cuenta.replaceAll("[0-9]", "");
                                                
                                                if(tipo.equals("Ahorros - ")){
                                                    CuentaAhorros cuentaAho = new CuentaAhorros();
                                                    cuentaAho.setIdCuentaAhorros(idCuenta);

                                                    cuentaAho = (CuentaAhorros)contrCuentasAho.consultarUno(cuentaAho);
                                                    
                                                    jLabelTotal.setText("Disponible: " +cuentaAho.getSaldoCuentaAhorros()+" $");
                                                    
                                                }
                                                if(tipo.equals("Corriente -")){
                                                    CuentaCorriente cuentaCorr = new CuentaCorriente();
                                                    cuentaCorr.setIdCuentaCorriente(idCuenta);

                                                    cuentaCorr = (CuentaCorriente)contrCuentasCorr.consultarUno(cuentaCorr);
                                                    
                                                    jLabelTotal.setText("Disponible: " +cuentaCorr.getSaldoCuentaCorriente()+" $");
                                                    
                                                }
                                            }  
                                            });
    }         
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboCuenta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonRetirar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Retiros");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Monto:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");

        jComboCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCuentaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Cuenta:");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoActionPerformed(evt);
            }
        });

        jButtonRetirar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButtonRetirar.setText("Retirar");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTotal.setText("Disponible");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Retiro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButtonRetirar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButtonRetirar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoActionPerformed
 
    }//GEN-LAST:event_jTextFieldMontoActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        // TODO add your handling code here:
        String cuenta = (String)jComboCuenta.getSelectedItem(); 
        String idCuenta = cuenta.replaceAll("[^0-9]", "");
        String tipo = cuenta.replaceAll("[0-9]", "");
        
        float monto =  Float.parseFloat(jTextFieldMonto.getText());
        float total_cuenta;
        
        String clave = new String(jPasswordField.getPassword());
        
        if(clave.equals(cli.getContrasena())){
            if(tipo.equals("Ahorros - ")){
                CuentaAhorros cuentaAho = new CuentaAhorros();
                cuentaAho.setIdCuentaAhorros(idCuenta);

                cuentaAho = (CuentaAhorros)contrCuentasAho.consultarUno(cuentaAho);
                CuentaAhorros cuentaAho_aux = new CuentaAhorros(cuentaAho);
                total_cuenta = cuentaAho.getSaldoCuentaAhorros();
                if(total_cuenta < monto){
                    JOptionPane.showMessageDialog(null, "Fondos insuficientes. \nSaldo actual: "+cuentaAho.getSaldoCuentaAhorros()+"\nmonto solicitado: "+monto);
                }
                else{
                    cuentaAho_aux.setSaldoCuentaAhorros(total_cuenta-monto);
                    contrCuentasAho.modificar(cuentaAho, cuentaAho_aux);
                    contrBD.modificarCuentaAho(cuentaAho_aux);
                    JOptionPane.showMessageDialog(null, "Transacción exitosa. Su nuevo saldo es: "+cuentaAho_aux.getSaldoCuentaAhorros());
                }
            }
            if(tipo.equals("Corriente - ")){
                CuentaCorriente cuentaCorr = new CuentaCorriente();
                cuentaCorr.setIdCuentaCorriente(idCuenta);

                cuentaCorr = (CuentaCorriente)contrCuentasCorr.consultarUno(cuentaCorr);
                
                CuentaCorriente cuentaCorr_aux = new CuentaCorriente(cuentaCorr);
                total_cuenta = cuentaCorr.getSaldoCuentaCorriente();
                if(total_cuenta < monto){
                    JOptionPane.showMessageDialog(null, "Fondos insuficientes. \nSaldo actual: "+cuentaCorr.getSaldoCuentaCorriente()+"\nmonto solicitado: "+monto);
                }
                else{
                    cuentaCorr_aux.setSaldoCuentaCorriente(total_cuenta-monto);
                    contrCuentasCorr.modificar(cuentaCorr, cuentaCorr_aux);
                    contrBD.modificarCuentaCorr(cuentaCorr_aux);
                    JOptionPane.showMessageDialog(null, "Transacción exitosa. Su nuevo saldo es: "+cuentaCorr_aux.getSaldoCuentaCorriente());
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Clave incorrecta");
        }
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    private void jComboCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCuentaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboCuentaActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Retiros().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JComboBox<String> jComboCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
